// A comic source used to verify the reading loop end to end, with no real site involved.
//
// Everything it serves is generated locally: explore page, search results, chapter list and image
// bytes. That is deliberate — AGENTS.md forbids depending on real commercial comic sources or real
// accounts in tests, and it also means the end-to-end script cannot rot because somebody else's
// server changed.
//
// Follows SourceClassConvention: the class declaration starts at column 0, extends ComicSource, and
// exposes name/key/version as instance fields.

class DemoComicSource extends ComicSource {
  constructor() {
    super();
    this.name = "Demo Comic Source";
    this.key = "demo_comic_source";
    this.version = "1.0.0";
    this.url = "https://example.invalid/demo-comic-source";
    this.minAppVersion = "0.1.0";
  }

  // ---------------------------------------------------------------- explore / search

  async explore(options) {
    const page = options && options.page ? options.page : 1;
    const pageSize = 20;
    const start = (page - 1) * pageSize;
    const total = 42;
    const comics = [];

    for (let index = start; index < Math.min(start + pageSize, total); index++) {
      comics.push(this.comicOf("c" + (index + 1)));
    }

    return { comics: comics, maxPage: Math.ceil(total / pageSize) };
  }

  async search(keyword, options) {
    const page = options && options.page ? options.page : 1;
    if (!keyword || keyword.trim().length === 0) {
      return { comics: [], maxPage: 1 };
    }
    const matching = keyword.toLowerCase().indexOf("miss") >= 0
      ? []
      : [this.comicOf("c1"), this.comicOf("c2")];

    return { comics: matching, maxPage: page };
  }

  // ---------------------------------------------------------------- details

  async loadInfo(id) {
    const index = parseInt(id.replace("c", ""), 10);
    const comic = this.comicOf(id);
    return {
      title: comic.title,
      subtitle: "Sample subtitle " + index,
      description: "Generated by tools/test-sources/demo_comic_source.js for end-to-end checks.",
      tags: ["Demo", "Generated"],
      cover: comic.cover,
      maxPage: 3,
      // Chapters as a map of id -> title, insertion-ordered: the order a source publishes is not
      // sorted lexically, and the app must preserve it rather than re-sorting.
      chapters: {
        "ch1": "Chapter 1",
        "ch2": "Chapter 2",
        "ch3": "Chapter 3"
      }
    };
  }

  async loadChapters(id) {
    const info = await this.loadInfo(id);
    return info.chapters;
  }

  // ---------------------------------------------------------------- pages

  // One chapter is three pages. The image URLs are generated by `tools/test-images` and served from
  // the local directory the manual script installs, so sizes come from the real image pipeline.
  async loadPages(comicId, chapterId) {
    const pages = [];
    for (let index = 1; index <= 3; index++) {
      pages.push({
        index: index - 1,
        url: "file:///android_asset/test-images/page-" + index + ".jpg"
      });
    }
    return pages;
  }

  // ---------------------------------------------------------------- helpers

  comicOf(id) {
    const index = parseInt(id.replace("c", ""), 10);
    return {
      id: id,
      title: "Demo Comic " + index,
      subtitle: "Generated " + index,
      cover: "file:///android_asset/test-images/cover-" + index + ".jpg",
      tags: ["Demo"],
      maxPage: 3
    };
  }
}
